# Generated by Django 5.2.7 on 2025-10-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('mrp', models.CharField(max_length=50)),
                ('quality', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('net_quantity', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('mfg_month', models.CharField(max_length=20)),
                ('mfg_year', models.CharField(max_length=4)),
                ('gtin', models.CharField(max_length=14)),
                ('manufacturer', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='labels/')),
                ('csv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='labels.csvupload')),
            ],
        ),
    ]
