# Generated by Django 5.2.7 on 2025-10-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlabel',
            name='design_color',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
