# Generated by Django 5.2.7 on 2025-10-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_productlabel_design_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='barcode_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='labels.csvupload')),
            ],
        ),
    ]
