# Generated by Django 5.2.7 on 2025-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_barcodeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodeimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='barcodeimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
