# Generated by Django 5.2.7 on 2025-10-17 19:39

import labels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_remove_barcodeimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeimage',
            name='image',
            field=models.ImageField(upload_to=labels.models.overwrite_filename),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(upload_to=labels.models.overwrite_filename),
        ),
    ]
