# Generated by Django 5.2.7 on 2025-10-18 06:58

import labels.models
import labels.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_barcodeimage_image_alter_csvupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeimage',
            name='image',
            field=models.ImageField(storage=labels.storage.OverwriteStorage(), upload_to=labels.models.overwrite_filename),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(storage=labels.storage.OverwriteStorage(), upload_to=labels.models.overwrite_filename),
        ),
    ]
